import { EventInterestForm } from '../EventInterestForm';
import { ThemeToggle } from '../ThemeToggle';
import styles from '../event.module.css';
import visualStyles from '../visual-fixes.module.css';
import premium from '../premium.module.css';

const supplies=['Mochilas','Cuadernos','Lápices y plumas','Marcadores y crayones','Carpetas','Reglas','Barras de pegamento','Tijeras','Resaltadores','Borradores','Calculadoras','Otros útiles escolares esenciales'];
const expectations=[
  {title:'Cortes de cabello gratis para niños',body:'Un buen comienzo para el año escolar, por orden de llegada y mientras haya capacidad disponible.'},
  {title:'Útiles escolares + obsequios',body:'Artículos escolares útiles distribuidos mientras duren las donaciones.'},
  {title:'Comida, diversión + comunidad',body:'Un espacio acogedor para conocer vecinos, voluntarios, mentores y personas que apoyan a Asc3nd.'},
  {title:'Sin promesa de reservación',body:'Compartir tu interés ayuda al equipo a planear. No garantiza un servicio, artículo ni horario de llegada.'},
];
const missionItems=[['Mentoría','Adultos constantes que escuchan, orientan y ayudan a los jóvenes a ver más posibilidades.'],['Liderazgo','Oportunidades para que los jóvenes desarrollen confianza, responsabilidad y propósito.'],['Habilidades para la vida + atletismo','Experiencias prácticas que apoyan el crecimiento, bienestar, trabajo en equipo y resiliencia.'],['Conexión comunitaria','Familias, mentores, escuelas, iglesias, negocios y vecinos trabajando juntos por los jóvenes.']];
const ways=[
  {title:'Familias',body:'Avísale a Asc3nd que planeas asistir para que el equipo pueda estimar la demanda y prepararse responsablemente. Esto no reserva un corte ni útiles.'},
  {title:'Voluntarios y mentores',body:'Ayuda a crear un día acogedor para jóvenes y familias locales y mantente conectado con el trabajo de mentoría y liderazgo de Asc3nd.'},
  {title:'Negocios y socios comunitarios',body:'Apoya con útiles escolares, necesidades del evento, futuras oportunidades para jóvenes o una alianza de largo plazo con Asc3nd Collective.'},
];

export const metadata={title:'Community Cuts for Kids | Asc3nd Collective',description:'Evento comunitario de regreso a clases de Asc3nd Collective en Everett, Washington, con cortes de cabello gratis para niños, útiles escolares, obsequios, comida y comunidad.'};

export default function PaginaCommunityCuts(){
return <main className={`${styles.page} ${premium.pagePremium} event-theme-root`}>
<header className={styles.header}><div className={styles.brand} aria-label="Asc3nd Collective"><span className={styles.brandMain}>ASC<span>3</span>ND</span><span className={styles.brandSub}>COLLECTIVE</span></div><nav className={styles.nav} aria-label="Navegación del evento"><a href="#event">Evento</a><a href="#supplies">Útiles</a><a href="#why">Por qué Asc3nd</a><a className={`${styles.navCta} ${premium.navAction}`} href="#connect">Planeo asistir</a><a className={premium.languageLink} href="/">EN</a><ThemeToggle/></nav></header>
<section className={`${styles.hero} ${premium.heroPremium}`} id="event"><div className={styles.heroCopy}><p className={styles.eyebrow}>Asc3nd Collective presenta</p><h1>Community Cuts<br/>for Kids</h1><p className={styles.heroLead}>Fresh Fade, Fresh Grade — un día comunitario gratuito de regreso a clases enfocado en confianza, preparación y conexión.</p><div className={styles.eventFacts}><div><span>Fecha</span><strong>Domingo, 30 de agosto de 2026</strong></div><div><span>Hora</span><strong>12:00 PM–3:00 PM</strong></div><div><span>Lugar</span><strong>Tangles &amp; Locs</strong><small>7425 Hardeson Rd, Everett, WA 98203</small></div></div><div className={styles.heroActions}><a className={`${styles.primaryButton} ${premium.primaryAction}`} href="#connect">Avísanos que planeas asistir</a><a className={`${styles.secondaryButton} ${premium.secondaryAction}`} href="#supplies">Ayuda a equipar a un estudiante</a></div><p className={styles.pendingNote}><strong>Aviso de planificación:</strong> Este formulario ayuda a Asc3nd a estimar la asistencia. No reserva un corte. Los servicios y útiles son por orden de llegada mientras haya capacidad.</p></div><figure className={visualStyles.heroFigure}><img className={visualStyles.heroImage} src="https://asc3nd-interactive-document.vercel.app/images/community-cuts/tangles-locs-exterior.webp" alt="Exterior de Tangles and Locs, sede del evento Community Cuts for Kids en Everett"/></figure></section>
<section className={`${styles.section} ${premium.expectSection}`} aria-labelledby="expect-heading"><div className={`${styles.sectionIntro} ${premium.sectionHeading}`}><p className={styles.eyebrow}>Qué esperar</p><h2 id="expect-heading">Un día práctico de cuidado, preparación y comunidad.</h2><p>Asc3nd reúne a familias, barberos, voluntarios y personas de la comunidad para ayudar a los jóvenes a comenzar el año escolar preparados y valorados.</p></div><div className={premium.expectEditorial}><div aria-hidden="true"/><div>{expectations.map((item,index)=><article className={premium.expectItem} key={item.title}><span className={premium.expectNumber}>{String(index+1).padStart(2,'0')}</span><div><h3>{item.title}</h3><p>{item.body}</p></div></article>)}</div></div></section>
<section className={styles.section} id="supplies"><div className={`${styles.sectionIntro} ${premium.sectionHeading} ${premium.supplyIntro}`}><p className={styles.eyebrow}>Útiles para el Éxito</p><h2>Ayuda a un estudiante a comenzar el año preparado.</h2><p>La colecta de útiles escolares de Asc3nd se realiza del 15 de julio al 15 de agosto de 2026. La meta es sencilla: reunir artículos escolares útiles y entregarlos directamente a estudiantes y familias locales mediante la campaña de regreso a clases.</p></div><div className={premium.supplyList}>{supplies.map(item=><div className={premium.supplyItem} key={item}>{item}</div>)}</div><div className={styles.callout}><div><p className={styles.eyebrow}>¿Quieres ayudar?</p><h3>Dona útiles, participa como voluntario, patrocina o conviértete en socio.</h3></div><a className={`${styles.primaryButton} ${premium.primaryAction}`} href="#connect">Dile a Asc3nd cómo quieres ayudar</a></div></section>
<section className={`${styles.section} ${styles.why}`} id="why"><div className={`${styles.sectionIntro} ${premium.sectionHeading}`}><p className={styles.eyebrow}>Más allá de un evento</p><h2>Un corte de cabello y una mochila pueden ayudar a comenzar la escuela con confianza. El trabajo de Asc3nd continúa después de ese día.</h2></div><div className={premium.missionEditorial}>{missionItems.map(([title,body])=><article className={premium.missionItem} key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><blockquote className={`${styles.founderStory} ${premium.founderQuote}`}><p>Asc3nd Collective fue fundado por Otha y Elisha Minnifield con la convicción de que un mentor que se preocupa o una oportunidad positiva puede cambiar la dirección de la vida de un joven.</p></blockquote></section>
<section className={styles.section} data-theme-section="join"><div className={`${styles.sectionIntro} ${premium.sectionHeading}`}><p className={styles.eyebrow}>Formas de participar</p><h2>Hay más de una forma de estar presente.</h2></div><div className={premium.joinEditorial}>{ways.map(item=><article className={premium.joinItem} key={item.title}><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></section>
<section className={`${styles.section} ${styles.connect}`} id="connect"><div className={styles.connectCopy}><p className={styles.eyebrow}>Asistencia y apoyo</p><h2>Dinos si esperas asistir o si quieres ayudar.</h2><p>Tu respuesta ayuda a Asc3nd a prepararse para la asistencia y el apoyo comunitario. Enviar tu interés no reserva un corte ni garantiza útiles.</p><div className={styles.privacyNote} data-surface="note"><strong>La privacidad de los jóvenes importa.</strong><p>Este formulario público no solicita el nombre, edad, escuela, historia personal, información médica ni otros datos sensibles de un menor. El consentimiento para fotos, video, testimonios y participación juvenil se maneja por separado.</p></div></div><div className={premium.formSurface} data-surface="form"><EventInterestForm locale="es"/></div></section>
<section className={styles.faq} data-theme-section="faq"><div className={`${styles.sectionIntro} ${premium.sectionHeading}`}><p className={styles.eyebrow}>Detalles del evento</p><h2>Lo que las familias y quienes apoyan deben saber.</h2></div><dl><div><dt>¿Cuándo es el evento?</dt><dd>Domingo, 30 de agosto de 2026, de 12:00 PM a 3:00 PM.</dd></div><div><dt>¿Dónde será?</dt><dd>Tangles &amp; Locs, 7425 Hardeson Rd, Everett, WA 98203.</dd></div><div><dt>¿Qué está confirmado?</dt><dd>Cortes de cabello gratis para niños, útiles y obsequios escolares, comida, diversión y comunidad.</dd></div><div><dt>¿Este formulario reserva un corte?</dt><dd>No. Ayuda a Asc3nd a estimar el interés y prepararse. Los cortes y artículos del evento son por orden de llegada mientras haya capacidad y existencias.</dd></div><div><dt>¿Debo ingresar información sobre mi hijo/a?</dt><dd>No. No ingreses nombres, edades, escuelas, información médica, historias familiares ni otros detalles sensibles.</dd></div><div><dt>¿Quién puede donar útiles?</dt><dd>Miembros de la comunidad, negocios, iglesias, escuelas, equipos y organizaciones pueden expresar interés ahora. Las instrucciones verificadas de entrega se compartirán cuando estén finalizadas.</dd></div></dl></section>
<footer className={styles.footer}><div><span className={styles.brandMain}>ASC<span>3</span>ND</span><p>Empoderar a los jóvenes. Elevar futuros. Construir comunidad.</p></div><span className={styles.footerNote}>Community Cuts for Kids · Everett, Washington</span></footer>
</main>;
}