import { EventInterestForm } from '../EventInterestForm';
import styles from '../event.module.css';
import visualStyles from '../visual-fixes.module.css';
import premium from '../premium.module.css';

const supplies=['Mochilas','Cuadernos','Lápices y plumas','Marcadores y crayones','Carpetas','Reglas','Barras de pegamento','Tijeras','Resaltadores','Borradores','Calculadoras','Otros útiles escolares esenciales'];
const expectations=[{title:'Cortes de cabello gratis para niños',body:'Un buen comienzo para el año escolar, por orden de llegada y mientras haya capacidad disponible.'},{title:'Útiles escolares + obsequios',body:'Artículos escolares útiles distribuidos mientras duren las donaciones.'},{title:'Comida, diversión + comunidad',body:'Un espacio acogedor para convivir con vecinos, voluntarios, mentores y personas que apoyan a Asc3nd.'},{title:'Planea, no reserves',body:'Compartir tu asistencia ayuda al equipo a prepararse. No garantiza un servicio, artículo ni horario de llegada.'}];
const missionItems=[['Mentoría','Adultos constantes que escuchan, orientan y ayudan a los jóvenes a ver más posibilidades.'],['Liderazgo','Oportunidades para desarrollar confianza, responsabilidad y propósito.'],['Habilidades para la vida + atletismo','Experiencias prácticas que apoyan el crecimiento, bienestar, trabajo en equipo y resiliencia.'],['Conexión comunitaria','Familias, mentores, escuelas, iglesias, negocios y vecinos presentes alrededor de los jóvenes.']];
const ways=[{title:'Familias',body:'Avísale a Asc3nd que planeas asistir para que el equipo pueda estimar la demanda y prepararse responsablemente.'},{title:'Voluntarios y mentores',body:'Ayuda a crear un día acogedor para jóvenes y familias locales y mantente conectado con el trabajo de mentoría y liderazgo de Asc3nd.'},{title:'Negocios y socios comunitarios',body:'Apoya con útiles escolares, necesidades del evento, futuras oportunidades para jóvenes o una alianza de largo plazo con Asc3nd Collective.'}];
const googleDirections='https://www.google.com/maps/dir/?api=1&destination=7425+Hardeson+Rd%2C+Everett%2C+WA+98203';
const appleDirections='https://maps.apple.com/?daddr=7425+Hardeson+Rd%2C+Everett%2C+WA+98203&dirflg=d';

export const metadata={title:'Community Cuts for Kids | Asc3nd Collective',description:'Evento comunitario gratuito de regreso a clases en Everett con cortes de cabello para niños, útiles escolares, comida, obsequios y comunidad.',alternates:{canonical:'/es',languages:{en:'/',es:'/es'}},openGraph:{title:'Community Cuts for Kids | Asc3nd Collective',description:'Evento comunitario gratuito de regreso a clases en Everett con cortes de cabello para niños, útiles escolares, comida y comunidad.',url:'/es'},twitter:{card:'summary',title:'Community Cuts for Kids | Asc3nd Collective',description:'Evento comunitario gratuito de regreso a clases en Everett con cortes de cabello para niños, útiles escolares, comida y comunidad.'}};

export default function PaginaCommunityCuts(){return <main className={`${styles.page} ${premium.pagePremium}`}>
<header className={styles.header}><div className={styles.brand} aria-label="Asc3nd Collective"><span className={styles.brandMain}>ASC<span>3</span>ND</span><span className={styles.brandSub}>COLLECTIVE</span></div><nav className={styles.nav} aria-label="Navegación del evento"><a href="#event">Evento</a><a href="#before">Antes de ir</a><a href="#supplies">Útiles</a><a className={`${styles.navCta} ${premium.navAction}`} href="#connect">Planeo asistir</a><a className={premium.languageLink} href="/">EN</a></nav></header>
<section className={`${styles.hero} ${premium.heroPremium}`} id="event"><div className={styles.heroCopy}><p className={styles.eyebrow}>Asc3nd Collective presenta</p><h1>Community Cuts<br/>for Kids</h1><p className={premium.heroPromise}>Cortes de cabello gratis + útiles escolares para niños de la comunidad.</p><p className={styles.heroLead}>Fresh Fade, Fresh Grade — un día comunitario gratuito de regreso a clases enfocado en confianza, preparación y conexión.</p><div className={styles.eventFacts}><div><span>Fecha</span><strong>Domingo, 30 de agosto de 2026</strong></div><div><span>Hora</span><strong>12:00 PM–3:00 PM</strong></div><div><span>Lugar</span><strong>Tangles &amp; Locs</strong><small>7425 Hardeson Rd, Everett, WA 98203</small></div></div><div className={styles.heroActions}><a className={`${styles.primaryButton} ${premium.primaryAction}`} href="#connect">Planeo asistir</a><a className={`${styles.secondaryButton} ${premium.secondaryAction}`} href="#support">Ayudar al evento</a></div><p className={styles.pendingNote}><strong>Importante:</strong> Compartir tu asistencia ayuda a Asc3nd a prepararse. Los cortes y útiles son por orden de llegada mientras haya capacidad y existencias.</p></div><figure className={visualStyles.heroFigure} aria-label="Ubicación del evento Tangles and Locs"><div className={visualStyles.venuePhotoStack} role="img" aria-label="Exterior de Tangles and Locs, sede del evento Community Cuts for Kids en Everett"><img src="/images/tangles-locs-01.webp" alt=""/><img src="/images/tangles-locs-02.webp" alt=""/><img src="/images/tangles-locs-03.webp" alt=""/><img src="/images/tangles-locs-04.webp" alt=""/></div><div className={visualStyles.venueActions}><a className={visualStyles.venuePrimary} href={googleDirections} target="_blank" rel="noreferrer">Llévame allí</a><div className={visualStyles.venueSecondaryRow}><a className={visualStyles.venueSecondary} href={googleDirections} target="_blank" rel="noreferrer">Google Maps</a><a className={visualStyles.venueSecondary} href={appleDirections} target="_blank" rel="noreferrer">Apple Maps</a></div><p className={visualStyles.venueAddress}>Tangles &amp; Locs · 7425 Hardeson Rd, Everett, WA 98203</p></div></figure></section>
<section className={`${styles.section} ${premium.expectSection}`}><div className={`${styles.sectionIntro} ${premium.sectionHeading}`}><p className={styles.eyebrow}>Qué habrá</p><h2>Un día práctico de cuidado, preparación y comunidad.</h2><p>Las familias pueden recibir apoyo para el regreso a clases y conectar con personas que quieren que los jóvenes comiencen el año preparados y valorados.</p></div><div className={premium.expectEditorial}><div aria-hidden="true"/><div>{expectations.map((item,index)=><article className={premium.expectItem} key={item.title}><span className={premium.expectNumber}>{String(index+1).padStart(2,'0')}</span><div><h3>{item.title}</h3><p>{item.body}</p></div></article>)}</div></div></section>
<section className={`${styles.section} ${premium.beforeSection}`} id="before"><div className={`${styles.sectionIntro} ${premium.sectionHeading}`}><p className={styles.eyebrow}>Antes de ir</p><h2>Todo lo confirmado en un solo lugar.</h2><p>Esta página solo publica detalles operativos después de que Asc3nd los verifique.</p></div><div className={premium.beforeGrid}><div><span>Cuándo</span><strong>Domingo, 30 de agosto · 12–3 PM</strong></div><div><span>Dónde</span><strong>Tangles &amp; Locs · Everett</strong></div><div><span>Disponibilidad</span><strong>Por orden de llegada mientras haya capacidad y existencias</strong></div><div><span>Planificación</span><strong>El formulario ayuda a Asc3nd a prepararse; no reserva un corte</strong></div></div><a className={`${styles.primaryButton} ${premium.directionAction}`} href={googleDirections} target="_blank" rel="noreferrer">Llévame allí</a></section>
<section className={premium.conversionBridge}><div><p className={styles.eyebrow}>¿Vienes con tu familia?</p><h2>Avísale a Asc3nd que planeas asistir.</h2></div><a className={`${styles.primaryButton} ${premium.primaryAction}`} href="#connect">Planeo asistir</a></section>
<section className={styles.section} id="supplies"><div className={`${styles.sectionIntro} ${premium.sectionHeading} ${premium.supplyIntro}`}><p className={styles.eyebrow}>Colecta de útiles escolares</p><h2>Ayuda a un estudiante a comenzar el año preparado.</h2><p>La colecta de Asc3nd se realiza del 15 de julio al 15 de agosto de 2026 para reunir artículos escolares útiles y entregarlos a estudiantes y familias locales.</p></div><div className={premium.supplyList}>{supplies.map(item=><div className={premium.supplyItem} key={item}>{item}</div>)}</div><div className={styles.callout}><div><p className={styles.eyebrow}>¿Quieres ayudar?</p><h3>Dona útiles, participa como voluntario, patrocina o conviértete en socio.</h3><p className={premium.calloutNote}>Las instrucciones públicas de entrega se agregarán aquí cuando Asc3nd las confirme.</p></div><a className={`${styles.primaryButton} ${premium.primaryAction}`} href="#connect">Dile a Asc3nd cómo quieres ayudar</a></div></section>
<section className={`${styles.section} ${styles.why}`} id="why"><div className={`${styles.sectionIntro} ${premium.sectionHeading}`}><p className={styles.eyebrow}>Esto es más grande que un solo día</p><h2>Asc3nd existe para ayudar a los jóvenes a seguir avanzando después del evento.</h2></div><div className={premium.missionEditorial}>{missionItems.map(([title,body])=><article className={premium.missionItem} key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><blockquote className={`${styles.founderStory} ${premium.founderQuote}`}><p>Asc3nd Collective fue fundado por Otha y Elisha Minnifield con la convicción de que un mentor que se preocupa o una oportunidad positiva puede cambiar la dirección de la vida de un joven.</p></blockquote></section>
<section className={styles.section} id="support"><div className={`${styles.sectionIntro} ${premium.sectionHeading}`}><p className={styles.eyebrow}>¿Quieres ayudar?</p><h2>Elige cómo quieres participar.</h2></div><div className={premium.joinEditorial}>{ways.map(item=><article className={premium.joinItem} key={item.title}><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></section>
<section className={`${styles.section} ${styles.connect}`} id="connect"><div className={styles.connectCopy}><p className={styles.eyebrow}>Asistencia y apoyo</p><h2>Dinos si planeas asistir o si quieres ayudar.</h2><p>Tu respuesta ayuda a Asc3nd a prepararse para la asistencia y el apoyo comunitario.</p><div className={styles.privacyNote} data-surface="note"><strong>La privacidad de los jóvenes importa.</strong><p>Este formulario público no solicita el nombre, edad, escuela, historia personal, información médica ni otros datos sensibles de un menor.</p></div></div><div className={premium.formSurface} data-surface="form"><EventInterestForm locale="es"/></div></section>
<section className={styles.faq}><div className={`${styles.sectionIntro} ${premium.sectionHeading}`}><p className={styles.eyebrow}>Detalles del evento</p><h2>Lo que las familias y quienes apoyan deben saber.</h2></div><dl><div><dt>¿Cuándo es?</dt><dd>Domingo, 30 de agosto de 2026, de 12:00 PM a 3:00 PM.</dd></div><div><dt>¿Dónde será?</dt><dd>Tangles &amp; Locs, 7425 Hardeson Rd, Everett, WA 98203. Usa el botón Llévame allí junto a la foto para navegación con un toque.</dd></div><div><dt>¿Qué está confirmado?</dt><dd>Cortes de cabello gratis para niños, útiles y obsequios escolares, comida, diversión y comunidad.</dd></div><div><dt>¿Este formulario reserva un corte?</dt><dd>No. Ayuda a Asc3nd a prepararse. Los cortes y artículos son por orden de llegada mientras haya capacidad y existencias.</dd></div><div><dt>¿Debo ingresar información sobre mi hijo/a?</dt><dd>No. No ingreses nombres, edades, escuelas, información médica, historias familiares ni otros detalles sensibles.</dd></div><div><dt>¿Dónde entrego los útiles?</dt><dd>Asc3nd todavía no ha publicado instrucciones públicas verificadas en esta página. Envía tu interés en donar para recibir seguimiento cuando los detalles estén finalizados.</dd></div></dl></section>
<footer className={styles.footer}><div><span className={styles.brandMain}>ASC<span>3</span>ND</span><p>Empoderar a los jóvenes. Elevar futuros. Construir comunidad.</p></div><span className={styles.footerNote}>Community Cuts for Kids · Everett, Washington</span></footer><a className={premium.mobileStickyCta} href="#connect">Planeo asistir</a>
</main>;}
