import { EventInterestForm } from './EventInterestForm';
import styles from './event.module.css';
import visualStyles from './visual-fixes.module.css';
import premium from './premium.module.css';

const supplies=['Backpacks','Notebooks','Pencils and pens','Markers and crayons','Folders','Rulers','Glue sticks','Scissors','Highlighters','Erasers','Calculators','Other school essentials'];
const waysToJoin=[{title:'Families',body:'Tell Asc3nd you plan to attend so the team can estimate demand and prepare responsibly. This does not reserve a haircut or supplies.'},{title:'Volunteers and mentors',body:'Help create a welcoming day for local youth and families, then stay connected to Asc3nd’s longer-term mentorship and leadership work.'},{title:'Businesses and community partners',body:'Support school supplies, event needs, future youth opportunities, or a longer-term partnership with Asc3nd Collective.'}];
const expectations=[{title:'Free haircuts for kids',body:'A fresh start for the school year, provided first come, first served while event capacity lasts.'},{title:'School supplies + giveaways',body:'Useful school essentials distributed while donated supplies last.'},{title:'Food, fun + community',body:'A welcoming place to meet neighbors, volunteers, mentors, and Asc3nd supporters.'},{title:'Plan, don’t reserve',body:'Sharing your attendance helps the team prepare. It does not guarantee a service, item, or arrival time.'}];
const missionItems=[['Mentorship','Consistent adults who listen, guide, and help young people see more possibilities.'],['Leadership','Opportunities for youth to build confidence, responsibility, and purpose.'],['Life skills + athletics','Practical experiences that support growth, wellness, teamwork, and resilience.'],['Community connection','Families, mentors, schools, churches, businesses, and neighbors showing up around young people together.']];
const googleDirections='https://www.google.com/maps/dir/?api=1&destination=7425+Hardeson+Rd%2C+Everett%2C+WA+98203';
const appleDirections='https://maps.apple.com/?daddr=7425+Hardeson+Rd%2C+Everett%2C+WA+98203&dirflg=d';
const mapEmbed='https://www.google.com/maps?q=7425+Hardeson+Rd,+Everett,+WA+98203&output=embed';

export default function CommunityCutsForKidsPage(){return <main className={`${styles.page} ${premium.pagePremium}`}>
<header className={styles.header}><div className={styles.brand} aria-label="Asc3nd Collective"><span className={styles.brandMain}>ASC<span>3</span>ND</span><span className={styles.brandSub}>COLLECTIVE</span></div><nav className={styles.nav} aria-label="Event navigation"><a href="#event">Event</a><a href="#before">Before you go</a><a href="#supplies">Supplies</a><a className={`${styles.navCta} ${premium.navAction}`} href="#connect">Plan to attend</a><a className={premium.languageLink} href="/es">ES</a></nav></header>

<section className={`${styles.hero} ${premium.heroPremium}`} id="event"><div className={styles.heroCopy}><p className={styles.eyebrow}>Asc3nd Collective presents</p><h1>Community Cuts<br/>for Kids</h1><p className={premium.heroPromise}>Free haircuts + school supplies for local kids.</p><p className={styles.heroLead}>Fresh Fade, Fresh Grade — a free back-to-school community day built around confidence, preparation, and connection.</p><div className={styles.eventFacts}><div><span>Date</span><strong>Sunday, August 30, 2026</strong></div><div><span>Time</span><strong>12:00 PM–3:00 PM</strong></div><div><span>Location</span><strong>Tangles &amp; Locs</strong><small>7425 Hardeson Rd, Everett, WA 98203</small></div></div><div className={styles.heroActions}><a className={`${styles.primaryButton} ${premium.primaryAction}`} href="#connect">Plan to attend</a><a className={`${styles.secondaryButton} ${premium.secondaryAction}`} href="#support">Help the event</a></div><p className={styles.pendingNote}><strong>Good to know:</strong> Sharing your attendance helps Asc3nd prepare. Haircuts and supplies are first come, first served while capacity and supplies last.</p></div><figure className={visualStyles.heroFigure} aria-label="Tangles and Locs event location"><iframe className={visualStyles.venueMap} src={mapEmbed} title="Map showing Tangles and Locs in Everett, Washington" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><div className={visualStyles.venueActions}><a className={visualStyles.venuePrimary} href={googleDirections} target="_blank" rel="noreferrer">Navigate me there</a><div className={visualStyles.venueSecondaryRow}><a className={visualStyles.venueSecondary} href={googleDirections} target="_blank" rel="noreferrer">Google Maps</a><a className={visualStyles.venueSecondary} href={appleDirections} target="_blank" rel="noreferrer">Apple Maps</a></div><p className={visualStyles.venueAddress}>Tangles &amp; Locs · 7425 Hardeson Rd, Everett, WA 98203</p></div></figure></section>

<section className={`${styles.section} ${premium.expectSection}`} aria-labelledby="expect-heading"><div className={`${styles.sectionIntro} ${premium.sectionHeading}`}><p className={styles.eyebrow}>What happens there</p><h2 id="expect-heading">A practical day of care, preparation, and community.</h2><p>Families can come for back-to-school support and connect with people who want young people to begin the school year feeling prepared and seen.</p></div><div className={premium.expectEditorial}><div aria-hidden="true"/><div>{expectations.map((item,index)=><article className={premium.expectItem} key={item.title}><span className={premium.expectNumber}>{String(index+1).padStart(2,'0')}</span><div><h3>{item.title}</h3><p>{item.body}</p></div></article>)}</div></div></section>
<section className={`${styles.section} ${premium.beforeSection}`} id="before"><div className={`${styles.sectionIntro} ${premium.sectionHeading}`}><p className={styles.eyebrow}>Before you go</p><h2>Everything confirmed in one place.</h2><p>This page will only publish operational details after Asc3nd verifies them. For now, these are the confirmed facts families can rely on.</p></div><div className={premium.beforeGrid}><div><span>When</span><strong>Sunday, August 30 · 12–3 PM</strong></div><div><span>Where</span><strong>Tangles &amp; Locs · Everett</strong></div><div><span>Availability</span><strong>First come, first served while capacity and supplies last</strong></div><div><span>Planning</span><strong>The attendance form helps Asc3nd prepare; it is not a haircut reservation</strong></div></div><a className={`${styles.primaryButton} ${premium.directionAction}`} href={googleDirections} target="_blank" rel="noreferrer">Navigate me there</a></section>
<section className={premium.conversionBridge}><div><p className={styles.eyebrow}>Coming with your family?</p><h2>Let Asc3nd know you plan to attend.</h2></div><a className={`${styles.primaryButton} ${premium.primaryAction}`} href="#connect">Plan to attend</a></section>
<section className={styles.section} id="supplies"><div className={`${styles.sectionIntro} ${premium.sectionHeading} ${premium.supplyIntro}`}><p className={styles.eyebrow}>School supply drive</p><h2>Help a student start the year ready.</h2><p>Asc3nd’s school-supply collection runs July 15–August 15, 2026. The goal is simple: gather useful school essentials and place them directly into the hands of local students and families through the back-to-school campaign.</p></div><div className={premium.supplyList}>{supplies.map(item=><div className={premium.supplyItem} key={item}>{item}</div>)}</div><div className={styles.callout}><div><p className={styles.eyebrow}>Want to help?</p><h3>Donate supplies, volunteer, sponsor, or partner.</h3><p className={premium.calloutNote}>Verified public drop-off instructions will be added here as soon as Asc3nd confirms them.</p></div><a className={`${styles.primaryButton} ${premium.primaryAction}`} href="#connect">Tell Asc3nd how you want to help</a></div></section>
<section className={`${styles.section} ${styles.why}`} id="why"><div className={`${styles.sectionIntro} ${premium.sectionHeading}`}><p className={styles.eyebrow}>This is bigger than one day</p><h2>Asc3nd exists to help young people keep moving forward after the event ends.</h2></div><div className={premium.missionEditorial}>{missionItems.map(([title,body])=><article className={premium.missionItem} key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><blockquote className={`${styles.founderStory} ${premium.founderQuote}`}><p>Asc3nd Collective was founded by Otha and Elisha Minnifield from a belief that one caring mentor or one positive opportunity can change the direction of a young person’s life.</p></blockquote></section>
<section className={styles.section} id="support" aria-labelledby="join-heading"><div className={`${styles.sectionIntro} ${premium.sectionHeading}`}><p className={styles.eyebrow}>Want to help?</p><h2 id="join-heading">Choose the way you want to show up.</h2></div><div className={premium.joinEditorial}>{waysToJoin.map(item=><article className={premium.joinItem} key={item.title}><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></section>
<section className={`${styles.section} ${styles.connect}`} id="connect"><div className={styles.connectCopy}><p className={styles.eyebrow}>Attendance and support</p><h2>Tell us whether you plan to attend or want to help.</h2><p>Your response helps Asc3nd prepare for attendance and community support.</p><div className={styles.privacyNote} data-surface="note"><strong>Youth privacy matters.</strong><p>This public form does not ask for a child’s name, age, school, story, health information, or other sensitive personal information. Photo, video, testimonial, and youth participation consent are separate processes.</p></div></div><div className={premium.formSurface} data-surface="form"><EventInterestForm/></div></section>
<section className={styles.faq} aria-labelledby="faq-heading"><div className={`${styles.sectionIntro} ${premium.sectionHeading}`}><p className={styles.eyebrow}>Event details</p><h2 id="faq-heading">What families and supporters should know.</h2></div><dl><div><dt>When is the event?</dt><dd>Sunday, August 30, 2026, from 12:00 PM to 3:00 PM.</dd></div><div><dt>Where is it?</dt><dd>Tangles &amp; Locs, 7425 Hardeson Rd, Everett, WA 98203. Use the Navigate me there button beside the venue map for one-tap navigation.</dd></div><div><dt>What is confirmed?</dt><dd>Free haircuts for kids, school supplies and giveaways, food, fun, and community.</dd></div><div><dt>Does this form reserve a haircut?</dt><dd>No. The form helps Asc3nd estimate interest and prepare. Haircuts and event items are first come, first served while capacity and supplies last.</dd></div><div><dt>Should I enter information about my child?</dt><dd>No. Do not enter child names, ages, schools, health information, family stories, or other sensitive details. Any participation or media consent is handled separately.</dd></div><div><dt>Where do I drop off school supplies?</dt><dd>Asc3nd has not yet published verified public drop-off instructions on this page. Submit your interest in donating and the team can follow up when details are finalized.</dd></div></dl></section>
<footer className={styles.footer}><div><span className={styles.brandMain}>ASC<span>3</span>ND</span><p>Empower youth. Elevate futures. Build community.</p></div><span className={styles.footerNote}>Community Cuts for Kids · Everett, Washington</span></footer>
<a className={premium.mobileStickyCta} href="#connect">Plan to attend</a>
</main>;}
